// <auto-generated />
using System;
using InvestingExile.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestingExile.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004093007_AddLeagueItemPriceSnapshot")]
    partial class AddLeagueItemPriceSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestingExile.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailsId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name", "Variant")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InvestingExile.Domain.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("InvestingExile.Domain.PriceSnapshot", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("HourBucket")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ChaosValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("DivineValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("ListingCount")
                        .HasColumnType("integer");

                    b.HasKey("LeagueId", "ItemId", "HourBucket");

                    b.HasIndex("ItemId");

                    b.ToTable("PriceSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_PriceSnapshots_HourBucket", "\"HourBucket\" = (date_trunc('hour', \"HourBucket\" AT TIME ZONE 'UTC') AT TIME ZONE 'UTC')");
                        });
                });

            modelBuilder.Entity("InvestingExile.Domain.PriceSnapshot", b =>
                {
                    b.HasOne("InvestingExile.Domain.Item", "Item")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestingExile.Domain.League", "League")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("League");
                });

            modelBuilder.Entity("InvestingExile.Domain.Item", b =>
                {
                    b.Navigation("PriceSnapshots");
                });

            modelBuilder.Entity("InvestingExile.Domain.League", b =>
                {
                    b.Navigation("PriceSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
